#!/usr/bin/env python
import sys
import os
import warnings
from dotenv import load_dotenv
from datetime import datetime
import uvicorn
from .api import app # Import the FastAPI app

from tutor.src.tutor.crew import Tutor # No longer directly using Tutor here
from tutor.src.tutor.tools.database import init_db, insert_course_data, get_all_courses_with_lessons # Database functions used by API
os.makedirs('content', exist_ok=True)

load_dotenv()

warnings.filterwarnings("ignore", category=SyntaxWarning, module="pysbd")

"""
# The run() function is no longer needed, as FastAPI will handle the execution
def run():

    subject=str(input("Enter your topic here :) :"))
    inputs ={'topic':subject}
    
    try:
        init_db()
        result = Tutor().crew().kickoff(inputs=inputs)
        # Assuming result contains the structured lesson data generated by the crew
        # You might need to parse the markdown files or directly get the structured data if crewai supports it.
        # For now, let's assume `result` is a list of dictionaries matching the Lesson structure.
        
        # In a real scenario, you'd parse the generated markdown files to extract the Lesson objects.
        # For demonstration, let's assume the `result` from kickoff contains the structured data.
        # If the crew output is just text, you'd need another agent/tool to parse it into Lesson objects.
        
        # Placeholder for actual lesson data parsing from generated markdown files
        # lessons_data = [] # This needs to be populated by parsing the generated markdown files
        # For example, you might read each generated lesson_X.md file and parse its content into a Lesson object.
        # import glob
        # import json
        # for lesson_file in glob.glob('content/lesson_*.txt'):
        #     with open(lesson_file, 'r') as f:
        #         # Assuming the content of markdown file is a JSON string of Lesson object
        #         # This might require adjustment based on the actual output format
        #         try:
        #             lesson_content = json.loads(f.read())
        #             lessons_data.append(lesson_content)
        #         except json.JSONDecodeError:
        #             print(f"Warning: Could not decode JSON from {lesson_file}. Skipping.")

        # if lessons_data:
        #     insert_course_data(subject, lessons_data)
        # else:
        #     print("No lesson data found to insert into the database.")

        # Retrieve and print all data from the database
        print("\n--- All Courses and Lessons in Database ---")
        all_data = get_all_courses_with_lessons()
        if all_data:
            for course in all_data:
                print(f"Course Topic: {course['topic']}")
                for lesson_num, lesson in enumerate(course['lessons'], 1):
                    print(f"  Lesson {lesson_num}: {lesson['lesson_name']} (Level: {lesson['lesson_level']})")
                    for key, value in lesson['lesson_content'].items():
                        print(f"    {key.replace('_', ' ').title()}: {value}")
        else:
            print("Database is empty.")

    except Exception as e:
        raise Exception(f"An error occurred while running the crew: {e}")
 """  

if __name__ == "__main__":
    #run()
    uvicorn.run("tutor.src.tutor.api:app", host="0.0.0.0", port=8000, reload=True)